# Generated by Django 5.0.1 on 2026-01-20 13:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número identificador do lote', max_length=10, unique=True, verbose_name='Número do Lote')),
                ('tipo', models.CharField(choices=[('residencial', 'Residencial'), ('administracao', 'Administração')], default='residencial', max_length=20, verbose_name='Tipo')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Hidrometro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número serial do hidrômetro', max_length=20, unique=True, verbose_name='Número do Hidrômetro')),
                ('localizacao', models.CharField(blank=True, help_text='Descrição da localização física do hidrômetro', max_length=255, null=True, verbose_name='Localização')),
                ('data_instalacao', models.DateField(verbose_name='Data de Instalação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidrometros', to='consumo.lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Hidrômetro',
                'verbose_name_plural': 'Hidrômetros',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leitura', models.DecimalField(decimal_places=3, help_text='Valor da leitura em metros cúbicos', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Leitura (m³)')),
                ('data_leitura', models.DateTimeField(verbose_name='Data e Hora da Leitura')),
                ('periodo', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], max_length=10, verbose_name='Período')),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável pela Leitura')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='leituras/%Y/%m/%d/', verbose_name='Foto da Leitura')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('hidrometro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='consumo.hidrometro', verbose_name='Hidrômetro')),
            ],
            options={
                'verbose_name': 'Leitura',
                'verbose_name_plural': 'Leituras',
                'ordering': ['-data_leitura'],
                'unique_together': {('hidrometro', 'data_leitura', 'periodo')},
            },
        ),
    ]
