# Generated by Django 5.0.1 on 2026-01-20 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitura',
            name='leitura',
            field=models.DecimalField(decimal_places=3, help_text='Valor da leitura em metros cúbicos (máximo: 99999.999)', max_digits=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999.999)], verbose_name='Leitura (m³)'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='tipo',
            field=models.CharField(choices=[('residencial', 'Residencial'), ('administracao', 'Uso do Condomínio')], default='residencial', max_length=20, verbose_name='Tipo'),
        ),
    ]
