# Generated by Django 5.0.1 on 2026-03-24 23:03

from django.db import migrations, models


def aprovar_perfis_existentes(apps, schema_editor):
    UsuarioPerfil = apps.get_model('consumo', 'UsuarioPerfil')
    UsuarioPerfil.objects.all().update(situacao_acesso='aprovado')


def desfazer_aprovacao_perfis_existentes(apps, schema_editor):
    UsuarioPerfil = apps.get_model('consumo', 'UsuarioPerfil')
    UsuarioPerfil.objects.all().update(situacao_acesso='pendente')


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0006_usuarioperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioperfil',
            name='situacao_acesso',
            field=models.CharField(choices=[('pendente', 'Pendente de Aprovacao'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=20, verbose_name='Situacao do Acesso'),
        ),
        migrations.RunPython(aprovar_perfis_existentes, desfazer_aprovacao_perfis_existentes),
    ]
