# Generated by Django 5.0.1 on 2026-03-24 23:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0007_usuarioperfil_situacao_acesso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usuarioperfil',
            constraint=models.UniqueConstraint(condition=models.Q(('telefone_contato', ''), _negated=True), fields=('telefone_contato',), name='uniq_telefone_contato_nao_vazio'),
        ),
    ]
