# Generated by Django 5.0.1 on 2026-05-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0009_auth_user_email_ci_unique_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='email_proprietario',
            field=models.EmailField(blank=True, help_text='Email para receber relatórios', max_length=254, null=True, verbose_name='Email do Proprietário 1'),
        ),
        migrations.AddField(
            model_name='lote',
            name='email_proprietario_2',
            field=models.EmailField(blank=True, help_text='Opcional. Email adicional para receber relatórios', max_length=254, null=True, verbose_name='Email do Proprietário 2'),
        ),
    ]
