# Generated by Django 5.0.1 on 2026-05-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0010_lote_email_proprietario_lote_email_proprietario_2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'ordering': ['numero_sequencia', 'numero'], 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.AddField(
            model_name='lote',
            name='numero_sequencia',
            field=models.IntegerField(default=0, help_text='Campo automático para ordenação numérica correta dos lotes', verbose_name='Número de Sequência (para ordenação)'),
        ),
    ]
